- name: settng up application
  include_role:
    name: common
    tasks_from: app-setup.yaml

- name: maven app-setup.yaml
  include_role:
    name: common
    tasks_from: maven-setup.yaml

- name: import data
  tags:
  - import
  community.mysql.mysql_db:
    name: all
    login_user: root
    login_password: RoboShop@1
    login_host: mysql.sindhu.agency
    state: import
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql

- name: restart shipping
  tags:
  - import
  ansible.builtin.service:
    state: restarted
    name: shipping