- name: copying service file to system directory
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable and start Catalogue service
  ansible.builtin.service:
    name: catalogue
    state: started
    enabled: yes